name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - python = 3.10
  - jupyterlab
  - matplotlib
  - pandas
  - openpyxl
  - xlsxwriter
  - seaborn = 0.12.2
  - pandasdmx
  - requests
  - urllib3
  - wbgapi
  - pytest
  - sympy
  - prophet
  - plotly
  - scikit-learn