name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - python = 3.10
  - jupyterlab
  - matplotlib
  - pandas
  - openpyxl
  - xlsxwriter
  - seaborn
  - pandasdmx
  - requests
  - ssl
  - urllib3
  - shutil
  - re
  - datetime
  - os
  - glob
  - wbgapi
  - json